name: buildAndSendSignatures

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Full name'
        required: true
      email:
        description: 'Email address'
        required: true
      position:
        description: 'Job title'
        required: true
      linkedin:
        description: 'LinkedIn URL'
        required: false

env:
  GH_ACTIONS_ENV: true
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
jobs:
  build_and_send_signatures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create user data JSON with data received from Google Apps Script
        run: |
          mkdir -p data
          echo '{
          "name": "${{ github.event.inputs.name }}",
          "email": "${{ github.event.inputs.email }}",
          "position": "${{ github.event.inputs.position }}",
          "linkedin": "${{ github.event.inputs.linkedin }}"
          }' > data/user.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Render signatures
        run: |
          npm install
          node ./src/renderSignatures.js

      - name: Send emails
        id: send-emails
        run: |
          chmod u+x src/sendEmails.sh 
          ./src/sendEmails.sh ${{ steps.changed-files.outputs.signatures_to_build }}
          
